eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      path:
        paynow: /payment/paynow
  order-service:
    endpoints:
      path:
        place: /order/place
